version: '3.8'

services:
  emprega_backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: emprega_vale
      SECRET: 87f86702ae92e490bd2d2ba2608edea663dcbd7f108052816d3a6d7a15e130b4
      GIN_MODE: release
    ports:
      - 5000:5000
    depends_on:
      - database

  emprega_front:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80

  database:
    container_name: database
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emprega_vale