[default]
# APPLICATION SETTINGS
NAME = 'Emprega Vale'
HOST = "0.0.0.0"
PORT = 8000
DEBUG = true

# DATABASE SETTINGS
DB_USER = "postgres"
DB_PASS = "postgres"
DB_PORT = 5432
DB_NAME = "emprega_vale"
DB_HOST = "localhost"

ROUTES = [
    "emprega_vale.api.auth:init_app"
]

# SECURITY
JWT_ALG = 'HS512'
SECRET = 'e28d8cab79863696c25c7ec43d6aeefa255dd0b44d869a4c795a01f2489af426'
JWT_ACCESS_EXPIRE_MINUTES = 15
JWT_REFRESH_EXPIRE_MINUTES = 120