"""empty message

Revision ID: ebbfcb0fff19
Revises: 
Create Date: 2020-07-12 18:09:55.259365

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebbfcb0fff19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'group',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=True)
    op.create_index(op.f('ix_group_uid'), 'group', ['uid'], unique=True)
    op.create_table(
        'login',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
        sa.Column('password', sa.String(length=1024), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('group_id',), ['group.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_login_email'), 'login', ['email'], unique=False)
    op.create_index(op.f('ix_login_id'), 'login', ['id'], unique=True)
    op.create_index(op.f('ix_login_uid'), 'login', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_uid'), table_name='login')
    op.drop_index(op.f('ix_login_id'), table_name='login')
    op.drop_index(op.f('ix_login_email'), table_name='login')
    op.drop_table('login')
    op.drop_index(op.f('ix_group_uid'), table_name='group')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
